### PR TITLE
Add a notebook on testing

### PR DESCRIPTION
**Pull request by jl-wynen**

### CODE REVIEW

**Review by wpotrzebowski — APPROVED** [review]
I've read the notebook and it looks very good to me! I think it is on the right level for someone at intermediate level. 

You may consider adding solutions to the exercises in another folder. 
Histograming and Chi-square exercises may provide more explanation/hints on what to look for. I've also found small typo in " If this is ot clear enough for you". 

It may be good if someone else also reviews it but otherwise I think it is ready to merge.

**Comment by celinedurniak** [comment]
In addition to Wojtek's comments, I found 2 typos (marked in bold)

- A leap year is any year that is divisible by 4 unless it is also divisible by 100 and not by 400. The author of the function tried to be clever but is it **acutally** correct?

- In this exercise, we are looking at fitting a parabola using the method of least squares. There is a fundamental difference to the other exercises. Here, we generally cannot sensibly construct an expected output because the fit has to deal with **randomess**

The headings of the subsections in Testing could be moved one level up because they all start with 1.0

Why is the meaning of '*' in the title of section "Least Squares Fit"?

In the exercise about energy transfer, m_n is not defined

**Review by celinedurniak — APPROVED** [review]
In addition to Wojtek's comments, I found 2 typos (marked in bold)

- A leap year is any year that is divisible by 4 unless it is also divisible by 100 and not by 400. The author of the function tried to be clever but is it **acutally** correct?

- In this exercise, we are looking at fitting a parabola using the method of least squares. There is a fundamental difference to the other exercises. Here, we generally cannot sensibly construct an expected output because the fit has to deal with **randomess**

The headings of the subsections in Testing could be moved one level up because they all start with 1.0

Why is the meaning of '*' in the title of section "Least Squares Fit"?

In the exercise about energy transfer, _m_n_ is not defined

**Comment by jl-wynen** [comment]
Fixed the typos, defined m_n, and added more descriptions.

>  Why is the meaning of '*' in the title of section "Least Squares Fit"?

This was supposed to indicate that the exercise is a 'bonus'. Removed it because there is the additional info box.

> You may consider adding solutions to the exercises in another folder.

There are solutions in `solutions/5_testing/1_testing.ipynb`. I added solutions for the exercises in the guided part.

> The headings of the subsections in Testing could be moved one level up because they all start with 1.0

What do you mean? Does it show a '1.0' somewhere for you?

**Comment by celinedurniak** [comment]
@jl-wynen 

The subsections, I am talking about, are numbered 
1.0.1  Error Modes
1.0.1.1  Aside: Exceptions
1.0.2  Zeeman Splitting

**Comment by jl-wynen** [comment]
Ah, I see. I had this numbering disabled.

**Pull request merged**
